apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello1-deployment
spec:
  replicas : 2 
  selector:
      matchLabels:
        app: hello1
  template:
      metadata:
        name: hello1-pods
        labels: 
            app: hello1
      spec:
          containers:
              - name : hello1
                image: hello1:latest
                imagePullPolicy: Never
                env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: redis-secret
                      key: redis-password
                - name: REDIS_PORT
                  value: "6379"
                - name: REDIS_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: redis-config
                      key: redis1-url
---
apiVersion: v1
kind : Service
metadata:
    name: hello1-service
spec:
    type: ClusterIP
    selector:
      app: hello1
    ports:
      - port: 80
        targetPort: 8000

---
apiVersion: v1
kind : Service
metadata:
    name: hello1-service-nodeport
spec:
    type: NodePort
    selector:
      app: hello1
    ports:
      - port: 80
        targetPort: 8000
        nodePort: 30001

